import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import Inter from next/font/google
import "./globals.css";

const inter = Inter({
  subsets: ['latin'], // Specify the subsets you want to use
  weight: ['400', '700'], // Specify the weights you want to use
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
